# The purpose of this workflow is to publish the workspace's crates
# whenever a tag is created. This basically boils down to running
# `scripts/publish.rs` at the right time.

name: "Publish to crates.io"

on:
  push:
    tags:
    - 'v*'

jobs:
  publish:
    if: github.repository == 'bytecodealliance/cargo-component'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable && rustup default stable
    - run: |
        rustc ci/publish.rs
        ./publish publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
